# Config references:
# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    schedule:
      interval: "daily"
    assignees:
      - "reside-eng/platform-tools"
    reviewers:
      - "reside-eng/platform-tools"
    ignore:
      # Skip to match with Node 16 LTS
      - dependency-name: '@types/node'
        update-types: ['version-update:semver-major']
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "reside-eng/platform-tools"
    reviewers:
      - "reside-eng/platform-tools"
