name: 'Verify Git Tag'
description: 'Verify if a Git tag exists in a target repository'
inputs:
  package-directory:
    required: false
    description: >
      The directory where to find the package.json file to retrieve the version which is used in association with tag-format.
    default: './'
  tag-format:
    required: false
    description: >
      The Git tag format used to identify releases.
    default: 'v$version'
runs:
  using: 'node16'
  main: 'dist/index.js'
