name: Verify (dependabot)

on:
  pull_request_target:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    if: github.actor == 'dependabot[bot]'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          ref: refs/pull/${{ github.event.number }}/merge

      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Configure Package Manager
        run: |
          echo Configuring NPM_READ_TOKEN globally for .npmrc
          npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_READ_TOKEN }}
          npm whoami

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        uses: raulanatol/jest-coverage-comment-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jest-command: yarn test --coverage --silent

      - name: Build
        run: yarn build
